replicaCount: 1

image:
  repository: radeczu/apitestapp
  tag: latest

service:
  type: LoadBalancer
  port: 2137

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"